# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArgusADSL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(default='None', max_length=128)),
                ('ne_ip', models.GenericIPAddressField(default='0.0.0.0', protocol='IPv4')),
                ('tel_num', models.IntegerField(db_index=True, default=0)),
                ('address', models.CharField(max_length=256)),
                ('room', models.CharField(max_length=256)),
                ('iptv_login', models.CharField(db_index=True, max_length=10)),
                ('inet_login', models.CharField(db_index=True, max_length=10)),
                ('xdsl_slot', models.CharField(max_length=256)),
                ('xdsl_port', models.IntegerField(default=-1)),
            ],
        ),
    ]
