# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argus', '0004_auto_20170609_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='argusadsl',
            name='address',
            field=models.CharField(default='N/A', max_length=512),
        ),
        migrations.AlterField(
            model_name='argusadsl',
            name='city',
            field=models.CharField(default='N/A', max_length=512),
        ),
        migrations.AlterField(
            model_name='argusadsl',
            name='fio',
            field=models.CharField(default='N/A', max_length=512),
        ),
        migrations.AlterField(
            model_name='argusadsl',
            name='hostname',
            field=models.CharField(default='None', max_length=512),
        ),
        migrations.AlterField(
            model_name='argusadsl',
            name='inet_login',
            field=models.CharField(db_index=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='argusadsl',
            name='iptv_login',
            field=models.CharField(db_index=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='argusadsl',
            name='room',
            field=models.CharField(default='N/A', max_length=512),
        ),
        migrations.AlterField(
            model_name='argusadsl',
            name='xdsl_slot',
            field=models.CharField(default='N/A', max_length=512),
        ),
    ]
