# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 06:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argus', '0010_argusgpon'),
    ]

    operations = [
        migrations.CreateModel(
            name='ASTU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(db_index=True, default='', max_length=512, unique=True)),
                ('address', models.CharField(default='', max_length=512)),
                ('structure_level', models.CharField(default='', max_length=512)),
                ('ne_class', models.CharField(default='', max_length=512)),
                ('vendor', models.CharField(default='', max_length=512)),
                ('model', models.CharField(default='', max_length=512)),
                ('status', models.CharField(default='', max_length=512)),
                ('comment', models.CharField(default='', max_length=512)),
                ('ne_ip', models.GenericIPAddressField(db_index=True, protocol='IPv4')),
                ('category', models.CharField(default='', max_length=16)),
                ('segment', models.CharField(default='', max_length=512)),
                ('serial_number', models.CharField(default='', max_length=512)),
            ],
        ),
    ]
