# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argus', '0011_astu'),
    ]

    operations = [
        migrations.AddField(
            model_name='argusadsl',
            name='lira',
            field=models.CharField(default='N/A', max_length=32),
        ),
    ]
