# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='argusadsl',
            name='city',
            field=models.CharField(default='N/A', max_length=256),
        ),
        migrations.AlterField(
            model_name='argusadsl',
            name='tel_num',
            field=models.IntegerField(db_index=True, default=-1),
        ),
    ]
