# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argus', '0002_auto_20170609_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='argusadsl',
            name='fio',
            field=models.CharField(default='N/A', max_length=256),
        ),
        migrations.AlterField(
            model_name='argusadsl',
            name='address',
            field=models.CharField(default='N/A', max_length=256),
        ),
        migrations.AlterField(
            model_name='argusadsl',
            name='room',
            field=models.CharField(default='N/A', max_length=256),
        ),
        migrations.AlterField(
            model_name='argusadsl',
            name='xdsl_slot',
            field=models.CharField(default='N/A', max_length=256),
        ),
    ]
