# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argus', '0003_auto_20170609_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='argusadsl',
            name='tel_num',
            field=models.BigIntegerField(db_index=True, default=-1),
        ),
    ]
