# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-10 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argus', '0006_auto_20170610_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='argusadsl',
            name='tel_num',
            field=models.CharField(db_index=True, default='', max_length=16),
        ),
    ]
