# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 10:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('argus', '0013_client'),
        ('net', '0002_auto_20170621_1114'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineStatus',
            fields=[
                ('status', models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline')], default='OFFLINE', max_length=32)),
                ('astu', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='argus.ASTU')),
            ],
        ),
    ]
