# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 07:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('net', '0004_auto_20170624_1107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onlinestatus',
            name='astu',
        ),
        migrations.DeleteModel(
            name='OnlineStatus',
        ),
    ]
