# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 06:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('argus', '0014_astu_is_online'),
        ('net', '0005_auto_20170624_1244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='ne_ip',
        ),
        migrations.AddField(
            model_name='job',
            name='ne_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='argus.ASTU'),
            preserve_default=False,
        ),
    ]
