# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 10:04
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('net', '0007_job_meta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='meta',
        ),
        migrations.AddField(
            model_name='job',
            name='meta_info',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=''),
        ),
    ]
