# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 10:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('net', '0008_auto_20170626_1504'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='meta_info',
            new_name='meta',
        ),
    ]
