# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 15:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('net', '0009_auto_20170626_1505'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ('-created',)},
        ),
    ]
