# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 10:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('net', '0010_auto_20170626_2050'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credentials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(default='', max_length=512)),
                ('passw', models.CharField(default='', max_length=512)),
                ('enable_password', models.CharField(default='', max_length=512)),
                ('snmp_community', models.CharField(default='', max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(db_index=True, default='', max_length=512, unique=True)),
                ('address', models.CharField(default='', max_length=512)),
                ('vendor', models.CharField(default='', max_length=512)),
                ('model', models.CharField(default='', max_length=512)),
                ('ne_ip', models.GenericIPAddressField(db_index=True, protocol='IPv4')),
                ('credentials', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='net.Credentials')),
            ],
        ),
    ]
