# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('net', '0011_credentials_equipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='ne_ip',
            field=models.GenericIPAddressField(db_index=True, protocol='IPv4', unique=True),
        ),
    ]
