# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('net', '0013_auto_20170701_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='address',
        ),
        migrations.AlterField(
            model_name='equipment',
            name='hostname',
            field=models.CharField(default='', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='model',
            field=models.CharField(default='', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='vendor',
            field=models.CharField(default='', max_length=512, null=True),
        ),
    ]
