# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 07:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('net', '0015_auto_20170702_2210'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentSuggestCredentials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('was_checked', models.BooleanField(default=False)),
                ('credentials_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='net.Credentials')),
                ('equipment_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='net.Equipment')),
            ],
            options={
                'ordering': ('equipment_id',),
            },
        ),
    ]
