# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 08:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('net', '0017_job_script'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='script_name',
        ),
    ]
