# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 09:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('argus', '0014_astu_is_online'),
        ('net', '0018_remove_job_script_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='ne_id',
        ),
        migrations.AddField(
            model_name='job',
            name='ne',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='argus.ASTU'),
        ),
    ]
