# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 09:07
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('net', '0019_auto_20170705_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='ne_ids',
            field=django.contrib.postgres.fields.jsonb.JSONField(default='', null=True),
        ),
    ]
