# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 08:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('net', '0021_auto_20170705_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='credentials',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='net.Credentials'),
        ),
    ]
