# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 08:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('net', '0022_auto_20170706_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentsuggestcredentials',
            name='credentials_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='net.Credentials'),
        ),
        migrations.AlterField(
            model_name='equipmentsuggestcredentials',
            name='equipment_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='net.Equipment'),
        ),
    ]
