# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 08:51
from __future__ import unicode_literals

from django.db import migrations
import netfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('net', '0025_credentials_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='ip',
            field=netfields.fields.InetAddressField(db_index=True, default='10.10.10.1', max_length=39),
            preserve_default=False,
        ),
    ]
