# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 08:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('net', '0026_equipment_ip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='ip',
        ),
    ]
