# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 08:53
from __future__ import unicode_literals

from django.db import migrations
import netfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('net', '0027_remove_equipment_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='ne_ip',
            field=netfields.fields.InetAddressField(db_index=True, max_length=39),
        ),
    ]
